export default {
    PUBLISH: 'PUBLISH',
    CLOSE_EDITOR: 'CLOSE_EDITOR',
    CHANGE_SELECTION: 'CHANGE_SELECTION',
    START_EDITING: 'START_EDITING',
    APPEND_EDITOR: 'APPEND_EDITOR',
    START_RENAMING: 'START_RENAMING',
    RENAME: 'RENAME',
    DELETE_SELECTION: 'DELETE_SELECTION',
    UNDO: 'UNDO',
    REDO: 'REDO'
}